ani_grenoble_app_homepage:
    path:     /
    defaults: { _controller: AniGrenobleAppBundle:Default:index }

ani_grenoble_app_a_propos:
    path:     /a-propos
    defaults: { _controller: AniGrenobleAppBundle:Default:a_propos }

#ani_grenoble_app_annonce_view:
    #path:     /annonce/{id}
    #defaults: { _controller: AniGrenobleAppBundle:Default:view }
    #requirements:
        #id: \d*

ani_grenoble_app_annonce_add:
    path:      /add
    defaults:  { _controller: AniGrenobleAppBundle:Default:add }

ani_grenoble_app_annonce_edit:
    path:     /edit/{id}
    defaults: { _controller: AniGrenobleAppBundle:Default:edit }
    requirements:
        id: \d*

ani_grenoble_app_annonce_delete:
    path:     /delete/{id}
    defaults: { _controller: AniGrenobleAppBundle:Default:delete }
    requirements:
        id: \d*

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
